### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by kukui** [tpodlaski/copra#2]
* Coinbase Pro Asyncronous Websocket Client version:
master 2c3c06301df5f762699cacc06ab0909c20c318b1
* Python version: 
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

* Operating System:
macos sierra 10.13.6

### Description
When running the following script 
```
# heartbeat.py
import asyncio
from copra.websocket import Channel, Client

KEY = '<mykey>'
SECRET = '<mysecret>''
PASSPHRASE = '<mypassphrase>'

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    ws = Client(loop, Channel('heartbeat', 'BTC-USD'))
    try:
        loop.run_forever()
    except KeyboardInterrupt:
        loop.run_until_complete(ws.close())
        loop.close()

```

 I get the following exception related to ssl verification

commmand
```bash
python3 heartbeat.py
```
##traceback

```bash
Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.create_connection() done, defined at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py:681> exception=SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 804, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 830, in _create_connection_transport
    yield from waiter
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 505, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)
```

**Comment by tpodlaski** [comment]
Based on your configuration, your problem sounds a lot like  https://github.com/Rapptz/discord.py/issues/423#issuecomment-272093801. Can you verify that you have the certificate installed?
